#!/usr/bin/env node
/* skillrail — org-wide agent skill registry + cross-tool sync.
 * Canonical format: skills/<name>/SKILL.md (Anthropic Agent Skills compatible).
 * Zero runtime dependencies. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const CONFIG_FILE = 'skillrail.json';
const LOCK_FILE = 'skillrail.lock.json';
const BEGIN_MARK = '<!-- BEGIN SKILLRAIL MANAGED BLOCK -->';
const END_MARK = '<!-- END SKILLRAIL MANAGED BLOCK -->';

// ---------- helpers ----------
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);
const read = (f) => fs.readFileSync(f, 'utf8');
const exists = fs.existsSync;
function writeFile(f, content) {
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, content);
}
function loadJSON(f, fallback) {
  return exists(f) ? JSON.parse(read(f)) : fallback;
}
function fail(msg) { console.error(`error: ${msg}`); process.exit(1); }

function loadConfig(root) {
  const f = path.join(root, CONFIG_FILE);
  if (!exists(f)) fail(`no ${CONFIG_FILE} found — run "skillrail init" first`);
  return JSON.parse(read(f));
}

// ---------- SKILL.md frontmatter ----------
function parseSkill(dir) {
  const f = path.join(dir, 'SKILL.md');
  if (!exists(f)) return null;
  const raw = read(f);
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { name: path.basename(dir), meta: {}, body: raw.trim(), raw, dir, invalid: 'missing frontmatter' };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_-]+):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim().replace(/^["']|["']$/g, '');
    if (v.startsWith('[')) v = v.replace(/^\[|\]$/g, '').split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    meta[kv[1].toLowerCase()] = v;
  }
  return { name: meta.name || path.basename(dir), meta, body: m[2].trim(), raw, dir };
}

function loadSkills(root, cfg) {
  const src = path.join(root, cfg.source || 'skills');
  if (!exists(src)) fail(`source dir "${src}" not found`);
  return fs.readdirSync(src, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => parseSkill(path.join(src, d.name)))
    .filter(Boolean);
}

// ---------- adapters: canonical skill -> per-tool artifact ----------
// Each adapter returns [{file, content}] relative to project root.
const genNote = (s) => `<!-- generated by skillrail from ${path.relative(process.cwd(), s.dir)}/SKILL.md v${s.meta.version || '0'} — edit the source, not this file -->`;

const ADAPTERS = {
  claude: (s) => {
    const out = [];
    // copy the whole skill dir verbatim — Claude Code reads SKILL.md natively
    const walk = (d, rel) => {
      for (const e of fs.readdirSync(d, { withFileTypes: true })) {
        const p = path.join(d, e.name);
        if (e.isDirectory()) walk(p, path.join(rel, e.name));
        else out.push({ file: path.join('.claude', 'skills', s.name, rel, e.name), content: read(p) });
      }
    };
    walk(s.dir, '');
    return out;
  },
  cursor: (s) => [{
    file: path.join('.cursor', 'rules', `${s.name}.mdc`),
    content: `---\ndescription: ${s.meta.description || ''}\nalwaysApply: false\n---\n${genNote(s)}\n\n${s.body}\n`
  }],
  copilot: (s) => [{
    file: path.join('.github', 'instructions', `${s.name}.instructions.md`),
    content: `---\napplyTo: "**"\n---\n${genNote(s)}\n\n# ${s.name}\n> ${s.meta.description || ''}\n\n${s.body}\n`
  }],
  windsurf: (s) => [{
    file: path.join('.windsurf', 'rules', `${s.name}.md`),
    content: `---\ntrigger: model_decision\ndescription: ${s.meta.description || ''}\n---\n${genNote(s)}\n\n${s.body}\n`
  }],
  // AGENTS.md (Codex, Jules, Amp, etc.) — one managed block for all skills
  agentsmd: null, // handled specially in sync()
};

function agentsmdBlock(skills) {
  const parts = skills.map(s =>
    `### ${s.name} (v${s.meta.version || '0'})\n> ${s.meta.description || ''}\n\n${s.body}`);
  return `${BEGIN_MARK}\n## Org skills — managed by skillrail, do not edit by hand\n\n${parts.join('\n\n---\n\n')}\n${END_MARK}`;
}

function skillTargets(s, cfg) {
  const t = s.meta.targets;
  if (!t || t === 'all') return cfg.targets;
  const list = Array.isArray(t) ? t : [t];
  return cfg.targets.filter(x => list.includes(x));
}

// ---------- commands ----------
function cmdInit(root) {
  const cfgPath = path.join(root, CONFIG_FILE);
  if (exists(cfgPath)) fail(`${CONFIG_FILE} already exists`);
  writeFile(cfgPath, JSON.stringify({
    source: 'skills',
    targets: ['claude', 'cursor', 'copilot', 'agentsmd'],
    registry: ''
  }, null, 2) + '\n');
  fs.mkdirSync(path.join(root, 'skills'), { recursive: true });
  console.log(`created ${CONFIG_FILE} and skills/ — add a skill with "skillrail add <name>"`);
}

function cmdAdd(root, name) {
  if (!name || !/^[a-z0-9][a-z0-9-]*$/.test(name)) fail('usage: skillrail add <kebab-case-name>');
  const cfg = loadConfig(root);
  const dir = path.join(root, cfg.source, name);
  if (exists(dir)) fail(`skill "${name}" already exists`);
  writeFile(path.join(dir, 'SKILL.md'),
`---
name: ${name}
description: TODO — one clear sentence describing when an agent should use this skill.
version: 1.0.0
owner: TODO-team-or-person
targets: all
---

# ${name}

Instructions the agent follows when this skill applies.
`);
  console.log(`created ${path.relative(process.cwd(), dir)}/SKILL.md — edit it, then run "skillrail sync"`);
}

function compileAll(root, cfg) {
  const skills = loadSkills(root, cfg);
  const files = []; // {file, content, skill, target}
  for (const s of skills) {
    for (const t of skillTargets(s, cfg)) {
      if (t === 'agentsmd' || !ADAPTERS[t]) continue;
      for (const out of ADAPTERS[t](s)) files.push({ ...out, skill: s.name, target: t });
    }
  }
  const agentsSkills = skills.filter(s => skillTargets(s, cfg).includes('agentsmd'));
  return { skills, files, agentsSkills };
}

function cmdSync(root, dry) {
  const cfg = loadConfig(root);
  const lock = loadJSON(path.join(root, LOCK_FILE), { files: {}, installed: {} });
  const { skills, files, agentsSkills } = compileAll(root, cfg);
  if (!skills.length) fail('no skills found — add one with "skillrail add <name>"');
  let wrote = 0, skipped = 0;

  for (const f of files) {
    const abs = path.join(root, f.file);
    const cur = exists(abs) ? read(abs) : null;
    if (cur === f.content) { skipped++; continue; }
    if (!dry) writeFile(abs, f.content);
    lock.files[f.file] = { skill: f.skill, target: f.target, hash: sha(f.content) };
    console.log(`${dry ? '[dry] ' : ''}${cur === null ? 'create' : 'update'} ${f.file}`);
    wrote++;
  }

  if (cfg.targets.includes('agentsmd') && agentsSkills.length) {
    const abs = path.join(root, 'AGENTS.md');
    const block = agentsmdBlock(agentsSkills);
    let content = exists(abs) ? read(abs) : '# Agent instructions\n\n';
    content = content.includes(BEGIN_MARK)
      ? content.replace(new RegExp(`${BEGIN_MARK}[\\s\\S]*?${END_MARK}`), block)
      : content.trimEnd() + '\n\n' + block + '\n';
    if ((exists(abs) ? read(abs) : null) !== content) {
      if (!dry) writeFile(abs, content);
      lock.files['AGENTS.md'] = { skill: '*', target: 'agentsmd', hash: sha(content) };
      console.log(`${dry ? '[dry] ' : ''}update AGENTS.md (managed block, ${agentsSkills.length} skills)`);
      wrote++;
    } else skipped++;
  }

  // prune lock entries whose canonical skill no longer exists
  const names = new Set(skills.map(s => s.name));
  for (const [file, meta] of Object.entries(lock.files)) {
    if (meta.skill !== '*' && !names.has(meta.skill)) {
      if (!dry && exists(path.join(root, file))) fs.rmSync(path.join(root, file));
      delete lock.files[file];
      console.log(`${dry ? '[dry] ' : ''}remove ${file} (skill deleted)`);
    }
  }

  if (!dry) writeFile(path.join(root, LOCK_FILE), JSON.stringify(lock, null, 2) + '\n');
  console.log(`\n${skills.length} skills → ${cfg.targets.join(', ')} | ${wrote} written, ${skipped} already in sync${dry ? ' (dry run — nothing changed)' : ''}`);
}

function cmdStatus(root) {
  const cfg = loadConfig(root);
  const lock = loadJSON(path.join(root, LOCK_FILE), { files: {} });
  const { files, agentsSkills } = compileAll(root, cfg);
  const expected = new Map(files.map(f => [f.file, f.content]));
  if (cfg.targets.includes('agentsmd') && agentsSkills.length) expected.set('AGENTS.md', null); // block-level check below
  let clean = true;

  for (const [file, content] of expected) {
    const abs = path.join(root, file);
    const locked = lock.files[file];
    if (!exists(abs)) { console.log(`missing   ${file} — run sync`); clean = false; continue; }
    const cur = read(abs);
    if (file === 'AGENTS.md') {
      const want = agentsmdBlock(agentsSkills);
      const m = cur.match(new RegExp(`${BEGIN_MARK}[\\s\\S]*?${END_MARK}`));
      if (!m) { console.log(`missing   AGENTS.md managed block — run sync`); clean = false; }
      else if (m[0] !== want) { console.log(`stale     AGENTS.md managed block — run sync`); clean = false; }
      continue;
    }
    if (cur === content) continue;
    if (locked && sha(cur) !== locked.hash) { console.log(`drifted   ${file} — edited in place; changes will be LOST on sync (port them to the canonical skill)`); clean = false; }
    else { console.log(`stale     ${file} — canonical skill changed, run sync`); clean = false; }
  }
  if (clean) console.log('all targets in sync ✓');
  process.exit(clean ? 0 : 2);
}

function cmdCheck(root) {
  const cfg = loadConfig(root);
  const skills = loadSkills(root, cfg);
  let bad = 0;
  for (const s of skills) {
    const problems = [];
    if (s.invalid) problems.push(s.invalid);
    if (!s.meta.description || /TODO/.test(s.meta.description)) problems.push('description missing or TODO');
    if (s.meta.description && s.meta.description.length > 1024) problems.push(`description ${s.meta.description.length} chars (max 1024 — it goes in the agent's system prompt)`);
    if (!s.meta.version || !/^\d+\.\d+\.\d+$/.test(s.meta.version)) problems.push('version missing or not semver');
    if (!s.meta.owner || /TODO/.test(String(s.meta.owner))) problems.push('owner missing or TODO');
    if (s.meta.name !== path.basename(s.dir)) problems.push(`frontmatter name "${s.meta.name}" ≠ dir "${path.basename(s.dir)}"`);
    const lines = s.body.split('\n').length;
    if (lines > 500) problems.push(`body is ${lines} lines (keep under ~500; move detail to reference files)`);
    if (problems.length) { bad++; console.log(`✗ ${s.name}\n${problems.map(p => `    - ${p}`).join('\n')}`); }
    else console.log(`✓ ${s.name} v${s.meta.version} (${s.meta.owner})`);
  }
  console.log(`\n${skills.length - bad}/${skills.length} skills pass`);
  process.exit(bad ? 1 : 0);
}

function cmdPull(root, url, names) {
  const cfg = loadConfig(root);
  url = url || cfg.registry;
  if (!url) fail('usage: skillrail pull <git-url> [skill ...]  (or set "registry" in skillrail.json)');
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'skillrail-'));
  try {
    execFileSync('git', ['clone', '--depth', '1', url, tmp], { stdio: 'pipe' });
    const head = execFileSync('git', ['-C', tmp, 'rev-parse', '--short', 'HEAD']).toString().trim();
    // registry layout: skills/<name>/SKILL.md at repo root (or bare <name>/SKILL.md)
    const regSrc = exists(path.join(tmp, 'skills')) ? path.join(tmp, 'skills') : tmp;
    const available = fs.readdirSync(regSrc, { withFileTypes: true })
      .filter(d => d.isDirectory() && exists(path.join(regSrc, d.name, 'SKILL.md'))).map(d => d.name);
    const want = names.length ? names : available;
    const lock = loadJSON(path.join(root, LOCK_FILE), { files: {}, installed: {} });
    for (const n of want) {
      if (!available.includes(n)) { console.log(`skip ${n} — not in registry (has: ${available.join(', ')})`); continue; }
      fs.cpSync(path.join(regSrc, n), path.join(root, cfg.source, n), { recursive: true });
      lock.installed[n] = { from: url, commit: head };
      console.log(`pulled ${n} @ ${head}`);
    }
    writeFile(path.join(root, LOCK_FILE), JSON.stringify(lock, null, 2) + '\n');
    console.log('\nrun "skillrail sync" to distribute to targets');
  } finally { fs.rmSync(tmp, { recursive: true, force: true }); }
}

function cmdList(root) {
  const cfg = loadConfig(root);
  const lock = loadJSON(path.join(root, LOCK_FILE), { installed: {} });
  for (const s of loadSkills(root, cfg)) {
    const origin = lock.installed[s.name] ? ` [from ${lock.installed[s.name].from} @ ${lock.installed[s.name].commit}]` : '';
    console.log(`${s.name}  v${s.meta.version || '?'}  owner=${s.meta.owner || '?'}  targets=${skillTargets(s, cfg).join(',')}${origin}`);
  }
}

// ---------- main ----------
const [cmd, ...args] = process.argv.slice(2);
const root = process.cwd();
const commands = {
  init: () => cmdInit(root),
  add: () => cmdAdd(root, args[0]),
  sync: () => cmdSync(root, args.includes('--dry')),
  status: () => cmdStatus(root),
  check: () => cmdCheck(root),
  pull: () => cmdPull(root, args[0], args.slice(1)),
  list: () => cmdList(root),
};
if (!commands[cmd]) {
  console.log(`skillrail — one skill source, every agent surface

usage:
  skillrail init                    set up skillrail.json + skills/ in this repo
  skillrail add <name>              scaffold a new skill
  skillrail sync [--dry]            compile skills to all targets (.claude, .cursor, .github, AGENTS.md, ...)
  skillrail status                  show stale / drifted / missing targets (exit 2 if dirty — CI-friendly)
  skillrail check                   lint skills: description, owner, semver, size (exit 1 on fail)
  skillrail pull [git-url] [name…]  install skills from a git registry repo
  skillrail list                    list skills with version, owner, origin

targets: claude, cursor, copilot, windsurf, agentsmd`);
  process.exit(cmd ? 1 : 0);
}
commands[cmd]();
